name: ocean-modelling-litter-philab
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - jupyter
  - intake
  - intake-xarray
  - rasterio
  - pytorch==1.8.0
  - torchvision==0.9.0
  - hvplot
  - pip
  - pip:
      - pycurl
      - git+https://github.com/ESM-VFC/intake_zenodo_fetcher.git
      - scikit-image