name: eds-book
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pip:
        - jupyter-book==0.12.3
        - ghp-import
        - sphinx_togglebutton
        - sphinx_design
        - sphinxcontrib-applehelp==1.0.4
        - sphinxcontrib-bibtex==2.5.0
        - sphinxcontrib-devhelp==1.0.2
        - sphinxcontrib-htmlhelp==2.0.1
        - sphinxcontrib-jsmath==1.0.1
        - sphinxcontrib-qthelp==1.0.3
        - sphinxcontrib-serializinghtml==1.1.5
