name: eds-book
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - pip:
        - jupyter-book==0.15.1
        - ghp-import
        - Sphinx==4.5.0
        - sphinx_togglebutton==0.3.2
        - sphinx_design==0.3.0